# Generated by Django 3.1.7 on 2021-03-20 08:11

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Skill = apps.get_model('skills', 'Skill')
    User(username="joebloggs", email="joe@email.com", password="hunter2", firstname="Joe", lastname="Bloggs").save()
    Skill(skill_name="fishing", skill_hours="200", skill_username="joebloggs").save()

    User(username="janebloggs", email="jane@email.com", password="hunter2", firstname="Jane", lastname="Bloggs").save()
    Skill(skill_name="baking", skill_hours="110", skill_username="joebloggs").save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
